#!/bin/bash -eu

echo "mysql" > ${OPENSHIFT_WILDFLY_DIR}/test


if [ -f ${OPENSHIFT_WILDFLY_DIR}/standalone/configuration/keycloak-server.jpa.json ]; then
    mv ${OPENSHIFT_WILDFLY_DIR}/standalone/configuration/keycloak-server.jpa.json ${OPENSHIFT_WILDFLY_DIR}/standalone/configuration/keycloak-server.json
fi

sed -i 's|java:jboss/datasources/KeycloakDS|java:jboss/datasources/MySQLDS|g' ${OPENSHIFT_WILDFLY_DIR}/standalone/configuration/keycloak-server.json
